import { NextRequest, NextResponse } from 'next/server';
import { registerAdminUser } from '../../../controllers/userController';
import { searchUsers } from '../../../models/user';

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const query = searchParams.get('search') || '';

    // Searches local DB representation for display
    const results = await searchUsers(query);
    return NextResponse.json(results, { status: 200 });
  } catch (err: any) {
    console.error('[API/Users] GET Error:', err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    // Payload expectation: keycloak_id (generated by frontend using crypto.randomUUID), username, name, email, password
    const result = await registerAdminUser(body);

    if (!result.success) {
      return NextResponse.json({ error: result.error }, { status: result.statusCode || 400 });
    }

    return NextResponse.json(result.data, { status: 201 });
  } catch (err: any) {
    console.error('[API/Users] POST Error:', err);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
