export interface User {
    id?: number; // Optional as it's typically auto-generated by the DB
    name: string;
    email: string;
    nickname: string;
    password: string; // In a real app, this would be hashed
}
